### ISSUE TITLE
'Number of alignments skipped due to not being useful'

### ISSUE THREAD

**Issue by Puriney** [10XGenomics/vartrix#32]
Hello vartrix team,
I was wondering what does the 'Number of alignments skipped due to not being useful' means, as the majority of my alignments fall into this category.
Thanks.

**Comment by pmarks** [comment]
Many alignments in the BAM file produced by STAR have long 'refskip' cigar entries which cause a large gap in the alignment where no read bases are aligned to the reference. STAR creates lots of these records.  If one of these gaps covers the SNP location, then the read is 'skipped due to not being useful', because it didn't actually contain the variant position.
