### ISSUE TITLE
Feature request: consensus allele counting

### ISSUE THREAD

**Issue by chrisamiller** [10XGenomics/vartrix#5]
In cases where there is more than one read with the same CB/UB combination, it's possible to have a situation where multiple alleles are present, despite the reads coming from a single molecule.  Our suggestion would be to:

a) use a consensus when possible.  If 75% of the reads support one allele, then choose that allele and assume the others are errors (or maybe even use higher threshold - 90%?)

b) if the consensus threshold is not reached, consider the read ambiguous and do not include it in the reported counts.

Would be great to see this in a future version!

**Comment by ifiddes-10x** [comment]
I am thinking about how to do this. Do you have an example in the datasets we have been working with where this occurs? If I am understanding correctly, the only way this is possible is if a sequencing error converts the alt back to ref.

In terms of the tool, I think I could add a `--rna` flag that tells VarTrix to expect a UB tag in the BAM and then it can take that info into account. For other single cell technologies, there are not UMIs to work with.

**Comment by sridnona** [comment]
UPN `782328` has some of these barcodes that did not reach consensus threshold at loci `21    43104346 ` 
```
ACGATGTTCTGTGCAA-2
AGCTCCTAGGCCCTCA-1
TACTCATTCACGACTA-2
TCTCTAATCCAGGGCT-1 
```

### Additional information 
```
readname	CB_tag	UB_tag	allele 
A00228:200:H3LY3DSXX:1:2224:7808:1579    ACGATGTTCTGTGCAA-2    TCATTATCAT    ref
A00228:200:H3LY3DSXX:4:1527:2031:19132    ACGATGTTCTGTGCAA-2    TCATTATCAT    alt
A00228:200:H3LY3DSXX:2:2636:7997:3850    AGCTCCTAGGCCCTCA-1    ACAAACACAG    alt
A00228:200:H3LY3DSXX:4:2242:30364:27680    AGCTCCTAGGCCCTCA-1    ACAAACACAG    ref
A00228:200:H3LY3DSXX:4:2369:23529:19445    TACTCATTCACGACTA-2    TGGCACATCG    alt
A00228:200:H3LY3DSXX:4:2431:29342:31015    TACTCATTCACGACTA-2    TGGCACATCG    ref
A00228:200:H3LY3DSXX:3:2551:11153:26287    TCTCTAATCCAGGGCT-1    ATTTACCGGC    ref
A00228:200:H3LY3DSXX:1:2571:22797:26663    TCTCTAATCCAGGGCT-1    ATTTACCGGC    ref
A00228:200:H3LY3DSXX:3:1314:17219:35916    TCTCTAATCCAGGGCT-1    ATTTACCGGC    alt
A00228:200:H3LY3DSXX:1:1577:25292:4742    TCTCTAATCCAGGGCT-1    ATTTACCGGC    alt
A00228:200:H3LY3DSXX:2:1229:25590:32095    TCTCTAATCCAGGGCT-1    ATTTACCGGC    alt

 
```

Thank you.

**Comment by ifiddes-10x** [comment]
This is an interesting case. I am not sure what is going on here yet. This locus has two retroposed pseudogene copies, and these CB/UMI pairs are showing reads with the expected alt (A) as well as reads with an unexpected alt (C). I don't see the C alt in any of the WGS data. The identity of the retroposed copies is low enough that I don't think those are causing the problem, although the MAPQ of all of these reads is 3 and they are randomly assigned primary and secondary through this region.

In theory, having multiple alleles for a given UMI/CB pair should not be possible. It isn't clear at this point whether this case is a chimera or a PCR error, but obviously seeing the same thing in 4 different UMI/CB pairs is quite intriguing. 

With the way the `binary-scoring` method is implemented in VarTrix right now, all of these 'C' containing reads will not contribute to the assignment because the ref score will equal the alt score. I think this is the right approach, rather than generating a consensus, but I am open to suggestions. VarTrix ignores multi-allelic sites right now for the same reason (how do you encode this information in a 2D matrix?).

**Comment by ifiddes-10x** [comment]
>We know sequencers have an error rate of around 0.5% (maybe a little lower). It's going to happen some of the time. That rate is even higher in some sequence contexts (like long homopolymer runs). It would be surprising to me if we didn't see it occasionally!

Yes, the error rate will lead to problem sometimes, totally.

>Agree that this is probably a region that's problematic in some way (either for base calling or because of misalignment)

But yes, this specific case is something more complicated.

>In some cases, those scores won't be equal, though, right (or am I misunderstanding)? Also, In a case with a different sequencing strategy, you could have 10 (or even 100) UBs with only one of them the "wrong" base. In that kind of situation, building a consensus representation seems like the ideal strategy.

The scores should be the same in the case where the error is a mismatch. In that case, the read will align with one mismatch to the ref allele and one mismatch to the alt allele, and so have an identical score.

>One general solution is to make things key off of chr:pos:allele (rather than just chr:pos).

That is an option, although a slightly tricky one because then the output matrix won't be the same size as the VCF. But, since I have included the `--out-variants` flag, it would work out I think.

I definitely see with your concerns about sequencing errors and needing to find a consensus. I can provide a user flag to set a consensus threshold possibly, as you suggested previously. I also am planning on putting in flags for mapping quality and whether the alignment is primary or not, which should help with this specific case.

**Comment by ifiddes-10x** [comment]
The open PR #21 should contain the features requested here. If you have a chance, do you want to check it out? It gives the expected behavior for the test case you provided (thanks for that!).

**Comment by chrisamiller** [comment]
Cool! Happy to test if you have a compiled version that contains the code from the PR. (I'm not familiar with rust and I'd probably blow through a couple of hours trying to figure that all out).

**Comment by ifiddes-10x** [comment]
I put it on the release page https://github.com/10XGenomics/vartrix/releases/tag/v1.1.0
