### ISSUE TITLE
error of umi

### ISSUE THREAD

**Issue by chenjy327** [10XGenomics/vartrix#78]
Hi, 
I am trying to use vartrix to analyze test data, and I have added the option of '--umi', 
`vartrix_linux --umi -v ./test_dna.vcf -b ./test_dna.bam -f ./test_dna.fa -c ./dna_barcodes.tsv -o ./matrix.mtx`
but the following error occurs, 
**08:52:44 [ERROR] The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs?**
may I ask what is the cause.

Thanks!

**Comment by pmarks** [comment]
Hi @chenjy327 - this is usually caused by not having any reads covering the SNPs you included in the VCF, on the barcodes you included. This can happen if there are any mismatches between genome version or between datasets.  One way to check would be to manually inspect the reads in the BAM file at the SNP locations listed in the VCF, perhaps using IGV.
